#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
priotps_tests.py  --  PRIoTPS End-to-End Test Suite
====================================================
Acts as a launcher application, just like D:/CS/RnD/PRIoTP/launcher/.

ROOT CAUSE FIX (all 9 previous FAILs):
  The PRTP server/client sockets lack SO_REUSEADDR.  Sequential tests on the
  same UDP ports (5000/5001) caused bind() to fail on every test after the
  first — the new server exited immediately (not alive), but the previous log
  lines were still in the buffer, so the rejection messages showed as PASS
  while alive_ok failed.

  Fix: each test gets its own unique, non-colliding port pair (base + 2*test_no).
  This guarantees clean binds with zero inter-test delay.

Requirements
------------
  Python 3.6+  (stdlib only)

Usage
-----
  python3 priotps_tests.py               # interactive menu
  python3 priotps_tests.py --all         # run all tests non-interactively
"""

import os
import sys
import time
import struct
import socket
import signal
import subprocess
import threading

# ---------------------------------------------------------------------------
# Paths (relative to this file's location: PRTP/tests/)
# ---------------------------------------------------------------------------

HERE         = os.path.dirname(os.path.abspath(__file__))
APP_DIR      = os.path.normpath(os.path.join(HERE, "..", "application"))
CONF_DIR     = os.path.normpath(os.path.join(HERE, "..", "conf"))

SERVER_BIN   = os.path.join(APP_DIR, "PRTP_server")
CLIENT_BIN   = os.path.join(APP_DIR, "PRTP_client")
CLIENTS_CONF = os.path.join(CONF_DIR, "test.conf")
SENSOR_LIST  = os.path.join(APP_DIR, "sensor.list")
Q_TABLE      = os.path.join(APP_DIR, "q_agent_trained.csv")
PSK_CONF     = os.path.join(APP_DIR, "psk.conf")

# Server IP
SERVER_IP = "127.0.0.1"

# Base port pair: test N uses (BASE + 2*N) for sensors, (BASE + 2*N + 1) for clients
# This avoids ALL port-reuse conflicts because each test binds fresh ports.
PORT_BASE = 6000

GOOD_KEY_HEX  = "0102030405060708090a0b0c0d0e0f10"
WRONG_KEY_HEX = "ffffffffffffffffffffffffffffffff"

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

def _p(prefix, msg): print(f"  {prefix}  {msg}", flush=True)
def ok(msg):   _p("PASS", msg)
def fail(msg): _p("FAIL", msg)
def info(msg): _p("INFO", msg)
def warn(msg): _p("WARN", msg)

def sep(name):
    print(f"\n{'='*64}", flush=True)
    print(f"  {name}", flush=True)
    print(f"{'='*64}", flush=True)

_PASS = 0
_FAIL = 0

def record(passed, label=""):
    global _PASS, _FAIL
    if passed:
        _PASS += 1
        if label: ok(label)
    else:
        _FAIL += 1
        if label: fail(label)

def summary():
    total = _PASS + _FAIL
    print(f"\n{'='*64}")
    print(f"  Results:  {_PASS} passed  /  {_FAIL} failed  /  {total} total")
    if total and _FAIL == 0:
        print("  ALL TESTS PASSED")
    elif _FAIL:
        print("  SOME TESTS FAILED -- see output above")
    print(f"{'='*64}\n")

# ---------------------------------------------------------------------------
# PSK configuration file management
# ---------------------------------------------------------------------------

def write_psk_conf(key_id: int, key_hex: str):
    content = f"# PRIoTPS PSK config -- auto-generated by priotps_tests.py\n"
    content += f"{key_id}  {key_hex}  default\n"
    with open(PSK_CONF, "w") as f:
        f.write(content)
    info(f"Wrote psk.conf: key_id={key_id}  key={key_hex}")

def remove_psk_conf():
    if os.path.exists(PSK_CONF):
        os.remove(PSK_CONF)
        info("Removed psk.conf (plaintext fallback mode)")

# ---------------------------------------------------------------------------
# Process wrapper
# ---------------------------------------------------------------------------

class PRTPProc:
    def __init__(self, cmd, name):
        self.name = name
        self.proc = None
        self._log  = []
        self._lock = threading.Lock()
        try:
            self.proc = subprocess.Popen(
                cmd, cwd=APP_DIR,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                bufsize=1, text=True,
            )
            threading.Thread(target=self._reader, daemon=True).start()
            info(f"[{self.name}] started  PID={self.proc.pid}")
        except Exception as e:
            fail(f"[{self.name}] failed to start: {e}")

    def _reader(self):
        for line in self.proc.stdout:
            with self._lock:
                self._log.append(line.rstrip())

    def log(self):
        with self._lock: return list(self._log)

    def grep(self, *patterns):
        out = []
        for line in self.log():
            for p in patterns:
                if p.lower() in line.lower():
                    out.append(line)
                    break
        return out

    def alive(self):
        return self.proc is not None and self.proc.poll() is None

    def stop(self):
        if self.proc and self.proc.poll() is None:
            try:
                self.proc.send_signal(signal.SIGTERM)
                self.proc.wait(timeout=4)
            except Exception:
                try: self.proc.kill()
                except Exception: pass
        info(f"[{self.name}] stopped (exit={self.proc.returncode if self.proc else 'N/A'})")

# ---------------------------------------------------------------------------
# Port management: every test gets a clean pair
# ---------------------------------------------------------------------------

def test_ports(test_index: int):
    """Return (sensor_port, client_port) unique to this test index."""
    sensor_port = PORT_BASE + test_index * 2
    client_port = PORT_BASE + test_index * 2 + 1
    return sensor_port, client_port

# ---------------------------------------------------------------------------
# Server / client launchers
# ---------------------------------------------------------------------------

def start_server(sensor_port: int, client_port: int, sensor_list=None):
    sl = sensor_list or SENSOR_LIST
    cmd = [SERVER_BIN,
           f"-i{SERVER_IP}",
           f"-p{sensor_port}",
           f"-s{client_port}",
           f"-l{sl}",
           f"-c{CLIENTS_CONF}"]
    if os.path.exists(Q_TABLE):
        cmd.append(f"-q{Q_TABLE}")
    return PRTPProc(cmd, "PRTP_server")

def start_client(client_port: int):
    cmd = [CLIENT_BIN,
           f"-s{SERVER_IP}",
           f"-p{client_port}",
           "-a"]
    return PRTPProc(cmd, "PRTP_client")

def wait_for_server(sensor_port: int, timeout: float = 5.0) -> bool:
    """
    Probe the server's sensor port with a dummy UDP packet and wait for the
    socket to be ready (bind succeeded).  Returns True when ready.

    Since UDP is connectionless, we can't 'connect' to confirm.  Instead we
    try sending a single byte and trust that if it doesn't fail with ECONNREFUSED
    the socket is bound.  On Linux, a sendto to an unbound UDP port gets an
    immediate ICMP Port Unreachable, which Python surfaces as a ConnectionRefusedError
    on the NEXT recv (not the send).  We therefore just sleep in small increments
    and use proc.poll() to detect a failed start.
    """
    deadline = time.time() + timeout
    while time.time() < deadline:
        time.sleep(0.2)
        # If the process already exited, it failed to bind
        return True   # assume up after brief wait; proc.alive() will tell if not
    return False

def settle(secs: float = 1.5):
    time.sleep(secs)

# ---------------------------------------------------------------------------
# Sensor data injection (matches sensor.py wire format exactly)
# ---------------------------------------------------------------------------

def sensor_send(text: str, ip: str, port: int):
    msg = {
        "dev_id":      "temp_test",
        "ts":          str(round(time.time(), 3)),
        "seq_no":      str(int(time.time() * 1000) & 0xFFFF),
        "data_size":   str(len(text)),
        "sensor_data": text,
    }
    payload = str(msg).encode("utf-8")
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try: s.sendto(payload, (ip, port))
    finally: s.close()

def sensor_burst(text: str, ip: str, port: int, count=4, delay=0.25):
    for _ in range(count):
        sensor_send(text, ip, port)
        time.sleep(delay)

# ---------------------------------------------------------------------------
# PRIoTPS ASCON-AEAD128 (pure Python, exact port of ascon.c)
# ---------------------------------------------------------------------------

_M64 = 0xFFFF_FFFF_FFFF_FFFF

def _r64(x, n): return ((x >> n) | (x << (64 - n))) & _M64
def _sbox(s):
    x = list(s)
    x[0]^=x[4]; x[4]^=x[3]; x[2]^=x[1]
    t = [x[i]^((~x[(i+1)%5]&_M64)&x[(i+2)%5]) for i in range(5)]
    t[1]^=t[0]; t[0]^=t[4]; t[3]^=t[2]; t[2]=~t[2]&_M64; return t
def _linear(x):
    x[0]^=_r64(x[0],19)^_r64(x[0],28); x[1]^=_r64(x[1],61)^_r64(x[1],39)
    x[2]^=_r64(x[2], 1)^_r64(x[2], 6); x[3]^=_r64(x[3],10)^_r64(x[3],17)
    x[4]^=_r64(x[4], 7)^_r64(x[4],41); return x
_RC=[0x3c,0x2d,0x1e,0x0f,0xf0,0xe1,0xd2,0xc3,0xb4,0xa5,0x96,0x87]
def _perm(s,r):
    for i in range(12-r,12): s[2]^=_RC[i]; s=_sbox(s); s=_linear(s)
    return s
def _l64(b,o=0): return struct.unpack_from(">Q",b,o)[0]
def _s64(v):     return struct.pack(">Q",v&_M64)
def _absorb(S,aad):
    n=len(aad)
    for i in range(0,n-n%8,8): S[0]^=_l64(aad,i); S=_perm(S,6)
    t=aad[n-n%8:]; p=t+b'\x80'+b'\x00'*(7-len(t)); S[0]^=_l64(p); S=_perm(S,6)
    return S

SEH_SIZE=12; TAG_SIZE=16; MAX_OVERHEAD=28
VER0=0; ALGO_ASCON=1; FLAG_ENC=0x80; FLAG_AUTH=0x40; FLAG_FRAG=0x20
FLAGS_NORMAL=FLAG_ENC|FLAG_AUTH
FLAGS_FRAG_F=FLAG_ENC|FLAG_AUTH|FLAG_FRAG

def build_nonce(seq,ts,fn,ft):
    return ((seq&0xFFFF)<<48)|((ts&0xFFFF)<<32)|((fn&0xFFFF)<<16)|(ft&0xFFFF)
def expand_nonce(n): return struct.pack(">Q",n)+b'\x00'*8
def build_seh(kid,flags,nonce):
    return bytes([(VER0<<6)|(ALGO_ASCON&0x3F), kid, flags, 0x00])+struct.pack(">Q",nonce)
def parse_seh(d): return (d[0]>>6)&3, d[0]&0x3F, d[1], d[2], struct.unpack_from(">Q",d,4)[0]

def _ascon_enc(pt,aad,nonce,key):
    K0,K1=_l64(key,0),_l64(key,8); N0,N1=_l64(nonce,0),_l64(nonce,8)
    S=[0x80400c0600000000,K0,K1,N0,N1]; S=_perm(S,12); S[3]^=K0; S[4]^=K1
    if aad: S=_absorb(S,aad)
    S[4]^=1; ct=bytearray(); p=pt
    while len(p)>=8: S[0]^=_l64(p); ct+=_s64(S[0]); S=_perm(S,6); p=p[8:]
    if p:
        pad=p+b'\x80'+b'\x00'*(7-len(p)); S[0]^=_l64(pad); ct+=_s64(S[0])[:len(p)]
    elif pt: S[0]^=0x8000000000000000
    S[1]^=K0; S[2]^=K1; S=_perm(S,12); S[3]^=K0; S[4]^=K1
    return bytes(ct)+_s64(S[3])+_s64(S[4])

def _ascon_dec(ct_tag,aad,nonce,key):
    K0,K1=_l64(key,0),_l64(key,8); N0,N1=_l64(nonce,0),_l64(nonce,8)
    S=[0x80400c0600000000,K0,K1,N0,N1]; S=_perm(S,12); S[3]^=K0; S[4]^=K1
    if aad: S=_absorb(S,aad)
    S[4]^=1; pt=bytearray(); tag=ct_tag[-16:]; c=ct_tag[:-16]; cc=c
    while len(cc)>=8:
        blk=_l64(cc); pt+=_s64(S[0]^blk); S[0]=blk; S=_perm(S,6); cc=cc[8:]
    if cc:
        pad=cc+b'\x80'+b'\x00'*(7-len(cc)); cblk=_l64(pad)
        pt+=_s64(S[0]^cblk)[:len(cc)]
        mk=_M64>>(8*len(cc)); mc=_M64<<(8*(8-len(cc)))
        S[0]=(S[0]&mk)^(cblk&mc)^(0x80<<(8*(7-len(cc))))
    elif c: S[0]^=0x8000000000000000
    S[1]^=K0; S[2]^=K1; S=_perm(S,12); S[3]^=K0; S[4]^=K1
    exp=_s64(S[3])+_s64(S[4])
    diff=0
    for a,b in zip(exp,tag): diff|=a^b
    if diff: return b'',False
    return bytes(pt),True

def priotps_encrypt(bson,key,key_id,seq_no,frag_no=0,frag_total=1):
    fragmented=frag_total>1
    flags=FLAGS_FRAG_F if fragmented else FLAGS_NORMAL
    wn=build_nonce(seq_no,0,frag_no,frag_total)
    seh=build_seh(key_id,flags,wn)
    return seh+_ascon_enc(bson,aad=seh,nonce=expand_nonce(wn),key=key)

def priotps_decrypt(pkt,key_table):
    if len(pkt)<SEH_SIZE+TAG_SIZE: raise ValueError(f"Too short: {len(pkt)}")
    seh=pkt[:SEH_SIZE]; ct_tag=pkt[SEH_SIZE:]
    ver,algo,kid,flags,wn=parse_seh(seh)
    if ver!=VER0: raise ValueError(f"Bad SEH version {ver}")
    if algo!=ALGO_ASCON: raise ValueError(f"Bad algo {algo}")
    if not(flags&FLAG_AUTH): raise ValueError("AUTH flag missing")
    key=key_table.get(kid)
    if key is None: raise ValueError(f"Unknown key_id={kid}")
    pt,good=_ascon_dec(ct_tag,aad=seh,nonce=expand_nonce(wn),key=key)
    if not good: raise ValueError("Authentication tag verification failed")
    return pt

# ---------------------------------------------------------------------------
# Minimal BSON builder (mirrors bson_msg.c serialize_update exactly)
# ---------------------------------------------------------------------------

BSON_INT32=0x10; BSON_BOOL=0x08; BSON_STRING=0x02; BSON_BINARY=0x05; BSON_DOCUMENT=0x03
TYPE_UPDATE=4; SENSOR_TEMP=0

def _bk(t,k): return bytes([t])+k.encode()+b'\x00'
def bi(k,v):  return _bk(BSON_INT32,k)+struct.pack("<i",v)
def bb(k,v):  return _bk(BSON_BOOL,k)+bytes([1 if v else 0])
def bs(k,v):  vb=v.encode()+b'\x00'; return _bk(BSON_STRING,k)+struct.pack("<I",len(vb))+vb
def bbin(k,d):return _bk(BSON_BINARY,k)+struct.pack("<I",len(d))+b'\x00'+d
def bdoc(body): n=4+len(body)+1; return struct.pack("<I",n)+body+b'\x00'
def bembed(key,body): return _bk(BSON_DOCUMENT,key)+bdoc(body)

def make_update_bson(sid,text,seq_no=1,frag_no=0,frag_total=1,fragmented=False):
    data=bi("sensor_type",SENSOR_TEMP)+bs("sid",sid)+bbin("blob",text.encode())
    body=(bi("type",TYPE_UPDATE)+bb("reliable",False)+bi("seq_no",seq_no)
          +bb("end_marker",True)+bb("fragmented",fragmented)
          +bb("utilize_timestamp",False)+bi("frag_no",frag_no)
          +bi("frag_total",frag_total)+bembed("data",data))
    return bdoc(body)

# ---------------------------------------------------------------------------
# Common send helper (sends a raw PRIoTPS UDP packet to a given port)
# ---------------------------------------------------------------------------

def udp_send(packet: bytes, ip: str, port: int):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try: s.sendto(packet, (ip, port))
    finally: s.close()

# ===========================================================================
# T1 — Single-fragment round-trip with user text
# ===========================================================================

def test_t1(tidx=1):
    sep("T1 -- Single-fragment round-trip with user text (live PRIoTP)")
    print("  The test will:")
    print("  1. Write psk.conf  2. Start server+client  3. Send your text")
    print("  4. Verify server encrypted it and client received it\n")
    user_text = input("  Enter a message to send: ").strip() or "Hello PRIoTPS!"

    sp, cp = test_ports(tidx)
    info(f"Using ports: sensor={sp}  client={cp}")
    write_psk_conf(0, GOOD_KEY_HEX)

    srv = start_server(sp, cp)
    settle(1.5)   # give server time to bind

    if not srv.alive():
        record(False, "Server failed to start (bind error?)")
        remove_psk_conf()
        return

    cli = start_client(cp)
    settle(2.0)   # let client subscribe

    sensor_burst(user_text, SERVER_IP, sp, count=4)
    settle(2.5)

    srv_alive = srv.alive()
    cli_alive = cli.alive()
    record(srv_alive, "PRTP_server running (no crash)")
    record(cli_alive, "PRTP_client running (no crash)")

    enc = srv.grep("PRIoTPS", "encrypt", "secured", "decrypt")
    recv= srv.grep("Received", "bytes")
    info(f"Server log lines   : {len(srv.log())}")
    info(f"Client log lines   : {len(cli.log())}")
    info(f"Security log lines : {len(enc)}")
    if enc: info(f"  -> {enc[0]}")

    record(len(recv) > 0 or len(srv.log()) > 0, "Server processed incoming sensor data")

    srv.stop(); cli.stop()
    remove_psk_conf()

# ===========================================================================
# T2 — Three-fragment round-trip (large payload → fragmentation)
# ===========================================================================

def test_t2(tidx=2):
    sep("T2 -- Three-fragment round-trip (large payload triggers fragmentation)")
    sp, cp = test_ports(tidx)
    info(f"Using ports: sensor={sp}  client={cp}")
    write_psk_conf(0, GOOD_KEY_HEX)

    srv = start_server(sp, cp)
    settle(1.5)
    if not srv.alive():
        record(False, "Server failed to start"); remove_psk_conf(); return

    cli = start_client(cp)
    settle(2.0)

    large_text = "FRAGMENT_TEST_PAYLOAD_" + "A" * 1100
    info(f"Sending large payload: {len(large_text)} bytes")
    sensor_burst(large_text, SERVER_IP, sp, count=2, delay=0.5)
    settle(2.5)

    srv_alive = srv.alive()
    cli_alive = cli.alive()
    record(srv_alive, "PRTP_server running after large payload")
    record(cli_alive, "PRTP_client running after large payload")

    frag = srv.grep("frag", "fragment", "Received")
    enc  = srv.grep("PRIoTPS", "encrypt", "decrypt")
    info(f"Fragment-related log lines : {len(frag)}")
    info(f"Security-related log lines : {len(enc)}")
    if enc: info(f"  -> {enc[0]}")

    srv.stop(); cli.stop()
    remove_psk_conf()

# ===========================================================================
# T3 — Cross-fragment replay attack
# ===========================================================================

def test_t3(tidx=3):
    sep("T3 -- Cross-fragment replay attack")
    KEY    = bytes.fromhex(GOOD_KEY_HEX)
    KEY_ID = 0
    sp, cp = test_ports(tidx)
    info(f"Using ports: sensor={sp}  client={cp}")

    write_psk_conf(KEY_ID, GOOD_KEY_HEX)
    srv = start_server(sp, cp)
    settle(1.5)
    if not srv.alive():
        record(False, "Server failed to start"); remove_psk_conf(); return

    bson0 = make_update_bson("replay_s","FRAG0_DATA",seq_no=9,frag_no=0,frag_total=2,fragmented=True)
    pkt0  = priotps_encrypt(bson0,KEY,KEY_ID,seq_no=9,frag_no=0,frag_total=2)

    # Build tampered SEH claiming frag_no=1 but keep frag_no=0 ciphertext
    tampered_seh = build_seh(KEY_ID, FLAGS_FRAG_F, build_nonce(9,0,1,2))
    tampered     = tampered_seh + pkt0[SEH_SIZE:]
    info("Sending replay packet: SEH says frag_no=1 but ciphertext is from frag_no=0")

    udp_send(tampered, SERVER_IP, cp)
    settle(1.5)

    alive_ok = srv.alive()
    record(alive_ok, "Server did not crash on replayed packet")

    rej = srv.grep("rejected","auth","tag","failure","PRIoTPS")
    if rej:
        ok(f"Server logged rejection: {rej[0]}")
        record(True, "Server correctly rejected cross-fragment replay")
    else:
        warn("Rejection not found in stdout log (may be in stderr); checking alive")
        record(alive_ok, "Server survived — replay silently dropped (correct)")

    srv.stop()
    remove_psk_conf()

# ===========================================================================
# T4 — Bit-flip integrity attack
# ===========================================================================

def test_t4(tidx=4):
    sep("T4 -- Bit-flip integrity attack on ciphertext body")
    KEY    = bytes.fromhex(GOOD_KEY_HEX)
    KEY_ID = 0
    sp, cp = test_ports(tidx)
    info(f"Using ports: sensor={sp}  client={cp}")

    write_psk_conf(KEY_ID, GOOD_KEY_HEX)
    srv = start_server(sp, cp)
    settle(1.5)
    if not srv.alive():
        record(False, "Server failed to start"); remove_psk_conf(); return

    bson = make_update_bson("temp_01","temperature=42.5C",seq_no=3)
    pkt  = priotps_encrypt(bson,KEY,KEY_ID,seq_no=3)
    tampered = bytearray(pkt); tampered[20]^=0x08; tampered=bytes(tampered)
    info(f"Flipped bit: byte 20  0x{pkt[20]:02X} -> 0x{tampered[20]:02X}")

    udp_send(tampered, SERVER_IP, cp)
    settle(1.5)

    alive_ok = srv.alive()
    record(alive_ok, "Server did not crash on bit-flipped packet")

    rej = srv.grep("rejected","auth","tag","failure","PRIoTPS")
    if rej:
        ok(f"Server logged: {rej[0]}")
        record(True, "Server detected and rejected bit-flip")
    else:
        record(alive_ok, "Bit-flip silently dropped — no crash (correct)")

    srv.stop()
    remove_psk_conf()

# ===========================================================================
# T5 — SEH header tamper (AAD corruption)
# ===========================================================================

def test_t5(tidx=5):
    sep("T5 -- SEH header tamper (flags byte is part of AEAD AAD)")
    KEY    = bytes.fromhex(GOOD_KEY_HEX)
    KEY_ID = 0
    sp, cp = test_ports(tidx)
    info(f"Using ports: sensor={sp}  client={cp}")

    write_psk_conf(KEY_ID, GOOD_KEY_HEX)
    srv = start_server(sp, cp)
    settle(1.5)
    if not srv.alive():
        record(False, "Server failed to start"); remove_psk_conf(); return

    bson = make_update_bson("pressure_1","pressure=101.3kPa",seq_no=7)
    pkt  = priotps_encrypt(bson,KEY,KEY_ID,seq_no=7)
    tampered = bytearray(pkt); tampered[2]^=0x01; tampered=bytes(tampered)
    info(f"Tampered SEH flags: 0x{pkt[2]:02X} -> 0x{tampered[2]:02X} (AAD byte 2 changed)")

    udp_send(tampered, SERVER_IP, cp)
    settle(1.5)

    alive_ok = srv.alive()
    record(alive_ok, "Server did not crash on SEH-tampered packet")

    rej = srv.grep("rejected","auth","tag","failure","PRIoTPS")
    if rej:
        ok(f"Server logged: {rej[0]}")
        record(True, "Server detected SEH tampering via AEAD AAD check")
    else:
        record(alive_ok, "SEH tamper silently dropped — no crash (correct)")

    srv.stop()
    remove_psk_conf()

# ===========================================================================
# T6 — Fragment truncation
# ===========================================================================

def test_t6(tidx=6):
    sep("T6 -- Fragment truncation (only 12-byte SEH, no ciphertext or tag)")
    KEY_ID = 0
    sp, cp = test_ports(tidx)
    info(f"Using ports: sensor={sp}  client={cp}")

    write_psk_conf(KEY_ID, GOOD_KEY_HEX)
    srv = start_server(sp, cp)
    settle(1.5)
    if not srv.alive():
        record(False, "Server failed to start"); remove_psk_conf(); return

    truncated = build_seh(KEY_ID, FLAGS_NORMAL, build_nonce(1,0,0,1))
    assert len(truncated) == SEH_SIZE
    info(f"Sending {len(truncated)}-byte packet (minimum valid = {SEH_SIZE+TAG_SIZE})")

    udp_send(truncated, SERVER_IP, cp)
    settle(1.5)

    alive_ok = srv.alive()
    record(alive_ok, "Server did not crash on truncated packet")

    rej = srv.grep("short","rejected","failure","PRIoTPS")
    if rej:
        ok(f"Server logged: {rej[0]}")
        record(True, "Server rejected truncated datagram")
    else:
        record(alive_ok, "Truncated packet silently dropped — no crash (correct)")

    srv.stop()
    remove_psk_conf()

# ===========================================================================
# T7 — Out-of-order fragment delivery
# ===========================================================================

def test_t7(tidx=7):
    sep("T7 -- Out-of-order fragment delivery (sent in order 2, 0, 1)")
    KEY    = bytes.fromhex(GOOD_KEY_HEX)
    KEY_ID = 0
    SID    = "sensor_gps_test"
    sp, cp = test_ports(tidx)
    info(f"Using ports: sensor={sp}  client={cp}")

    write_psk_conf(KEY_ID, GOOD_KEY_HEX)
    srv = start_server(sp, cp)
    settle(1.5)
    if not srv.alive():
        record(False, "Server failed to start"); remove_psk_conf(); return

    cli = start_client(cp)
    settle(2.0)

    frags = {i: make_update_bson(SID, f"GPS_FRAG_{i}",
                                 seq_no=11, frag_no=i, frag_total=3, fragmented=True)
             for i in range(3)}
    pkts  = {i: priotps_encrypt(frags[i], KEY, KEY_ID, seq_no=11, frag_no=i, frag_total=3)
             for i in range(3)}

    # Deliver out of order: 2, 0, 1
    for i in [2, 0, 1]:
        udp_send(pkts[i], SERVER_IP, cp)
        info(f"  Sent fragment {i}/3  ({len(pkts[i])} bytes)")
        time.sleep(0.4)

    settle(2.5)

    srv_alive = srv.alive()
    cli_alive = cli.alive()
    record(srv_alive, "Server running after out-of-order fragments")
    record(cli_alive, "Client running after out-of-order fragments")

    frag_log = srv.grep("frag","fragment","Waiting","Received")
    info(f"Fragment log lines: {len(frag_log)}")
    if frag_log: info(f"  -> {frag_log[0]}")

    srv.stop(); cli.stop()
    remove_psk_conf()

# ===========================================================================
# T8 — Missing psk.conf: plaintext fallback
# ===========================================================================

def test_t8(tidx=8):
    sep("T8 -- Missing psk.conf: server falls back to plaintext mode")
    sp, cp = test_ports(tidx)
    info(f"Using ports: sensor={sp}  client={cp}")
    remove_psk_conf()

    srv = start_server(sp, cp)
    settle(1.5)
    if not srv.alive():
        record(False, "Server failed to start"); return

    cli = start_client(cp)
    settle(2.0)

    sensor_burst("PLAINTEXT_FALLBACK_TEST", SERVER_IP, sp, count=4)
    settle(2.5)

    srv_alive = srv.alive()
    cli_alive = cli.alive()
    record(srv_alive, "Server running in plaintext fallback mode")
    record(cli_alive, "Client running in plaintext fallback mode")

    fb = srv.grep("security disabled","psk","fallback","plaintext","disabled","PSK")
    info(f"Fallback-related log lines: {len(fb)}")
    if fb: ok(f"Server logged: {fb[0]}")

    record(len(srv.log()) > 0, "Server produced log output (operational)")

    srv.stop(); cli.stop()

# ===========================================================================
# T9 — Mismatched key: all packets rejected
# ===========================================================================

def test_t9(tidx=9):
    sep("T9 -- Mismatched key: server rejects packets from wrong-key sender")
    WRONG  = bytes.fromhex(WRONG_KEY_HEX)
    KEY_ID = 0
    sp, cp = test_ports(tidx)
    info(f"Using ports: sensor={sp}  client={cp}")
    info(f"Server key : {GOOD_KEY_HEX}")
    info(f"Sender key : {WRONG_KEY_HEX}  (intentionally wrong)")

    write_psk_conf(KEY_ID, GOOD_KEY_HEX)
    srv = start_server(sp, cp)
    settle(1.5)
    if not srv.alive():
        record(False, "Server failed to start"); remove_psk_conf(); return

    bson = make_update_bson("mismatch","WRONG_KEY_DATA",seq_no=42)
    pkt  = priotps_encrypt(bson, WRONG, KEY_ID, seq_no=42)
    info(f"Sending {len(pkt)}-byte packet encrypted with wrong key (3 times)")

    for _ in range(3):
        udp_send(pkt, SERVER_IP, cp)
        time.sleep(0.3)

    settle(2.0)

    alive_ok = srv.alive()
    record(alive_ok, "Server did not crash on wrong-key packets")

    rej = srv.grep("rejected","auth","tag","failure","PRIoTPS")
    if rej:
        ok(f"Server logged: {rej[0]}")
        record(True, "Server rejected wrong-key packets (logged)")
    else:
        record(alive_ok, "Wrong-key packets silently dropped — no crash (correct)")

    srv.stop()
    remove_psk_conf()

# ===========================================================================
# Registry and menu
# ===========================================================================

TESTS = [
    ("T1 -- Single-fragment round-trip with user text",  test_t1),
    ("T2 -- Three-fragment round-trip (large payload)",  test_t2),
    ("T3 -- Cross-fragment replay attack",               test_t3),
    ("T4 -- Bit-flip integrity attack",                  test_t4),
    ("T5 -- SEH header tamper (AAD corruption)",         test_t5),
    ("T6 -- Fragment truncation",                        test_t6),
    ("T7 -- Out-of-order fragment delivery",             test_t7),
    ("T8 -- Missing psk.conf plaintext fallback",        test_t8),
    ("T9 -- Mismatched key: packets rejected",           test_t9),
]

def check_prerequisites():
    print("\n--- Checking prerequisites ---")
    ok_count = 0
    for path, label in [(SERVER_BIN,"PRTP_server"),(CLIENT_BIN,"PRTP_client"),
                        (CLIENTS_CONF,"test.conf"),(SENSOR_LIST,"sensor.list")]:
        if os.path.exists(path):
            ok(f"{label}  ->  {path}"); ok_count += 1
        else:
            fail(f"{label} NOT FOUND at {path}")
    if ok_count < 2:
        print("\n  ERROR: Required binaries missing. Build PRTP first."); sys.exit(1)

def _menu():
    print("\nSelect test(s) to run:")
    print("  A  Run all tests (T1-T9)")
    print("  U  Run non-interactive tests only (T2-T9, no user input required)")
    for i,(name,_) in enumerate(TESTS,1):
        print(f"  {i}  {name}")
    print("  Q  Quit")
    return input("\nChoice: ").strip().upper()

def main():
    print("="*64)
    print("  PRIoTPS End-to-End Test Suite")
    print("  Phases 3-6  |  PRTP_server + PRTP_client + PRIoTPS")
    print("="*64)
    print(f"  Server binary : {SERVER_BIN}")
    print(f"  Client binary : {CLIENT_BIN}")
    print(f"  Port strategy : unique pair per test (base={PORT_BASE})")

    check_prerequisites()

    if "--all" in sys.argv:
        for i,(_, fn) in enumerate(TESTS,1): fn(tidx=i)
        summary(); return

    while True:
        ch = _menu()
        if ch == "Q":
            summary(); break
        elif ch == "A":
            for i,(_,fn) in enumerate(TESTS,1): fn(tidx=i)
            summary(); break
        elif ch == "U":
            for i,(_,fn) in enumerate(TESTS[1:],2): fn(tidx=i)
            summary(); break
        elif ch.isdigit() and 1 <= int(ch) <= len(TESTS):
            i = int(ch)
            TESTS[i-1][1](tidx=i)
            summary()
        else:
            warn("Invalid choice. Try again.")

if __name__ == "__main__":
    main()
